format_version: v1.0
type: UniqueComponent
attributes: {id: cmsis}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CMSIS_DSP_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '430', y: '60', id: cmsis}
