configName: ATSAMC21E
folderName: ''
format_version: v1.0
frameworkPath: ../../Harmony3
processor: ATSAMC21E15A
projectName: ''
settings:
  PackageFilter: crypto;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMC21_DFP\3.5.83\samc21\atdf\ATSAMC21E15A.atdf
