format_version: v1.0
type: UniqueComponent
attributes: {id: tc1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: '48000000'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: '65534'}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2.0'}
- type: ElementPosition
  attributes: {x: '30', y: '300', id: tc1}
